language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
after_success:
  - coveralls
script:
  - python -m unittest tests/test-*.py
  - coverage run -m unittest -s tests/test-*.py
  - coverage report -m
