language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
after_success:
  - coveralls
script:
  - python -m pytest tests/test-*.py
  - coverage run --source=. -m pytest tests/test-*.py
  - coverage report -m
